input {
  tcp {
    port => 5000
    codec => json_lines
  }
  beats {
    port => 5044
  }
}

filter {
  if [service] {
    mutate {
      add_tag => ["edtech", "%{[service]}"]
    }
  }

  if [timestamp] {
    date {
      match => ["timestamp", "ISO8601", "yyyy-MM-dd HH:mm:ss"]
      target => "@timestamp"
      remove_field => ["timestamp"]
    }
  }

  if [level] {
    mutate {
      rename => { "level" => "log_level" }
      uppercase => ["log_level"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "edtech-%{[service]:logs}-%{+YYYY.MM.dd}"
    action => "index"
  }
}
