"""
Seed data for careers — 30+ comprehensive career entries covering all major fields
relevant to Indian school students (Class 8-12).
"""

CAREER_SEED_DATA = [
    # ── Engineering ──────────────────────────────────────────────────────────
    {
        "title": "Software Engineer",
        "category": "Engineering",
        "slug": "software-engineer",
        "overview": "Design, develop and maintain software applications. One of the highest-demand careers globally with excellent salaries and remote work opportunities.",
        "required_subjects": ["Mathematics", "Computer Science", "Physics"],
        "skills_required": ["Programming", "Data Structures", "Algorithms", "Problem Solving", "System Design"],
        "roadmap_steps": [
            {"step": 1, "label": "Class 10", "detail": "Strong foundation in Mathematics & Science"},
            {"step": 2, "label": "Class 11-12", "detail": "Choose PCM stream + start learning Python/C++"},
            {"step": 3, "label": "JEE Prep", "detail": "Crack JEE Mains/Advanced for top IITs/NITs"},
            {"step": 4, "label": "B.Tech CSE", "detail": "4-year Computer Science degree"},
            {"step": 5, "label": "Internships", "detail": "Build projects, intern at tech companies"},
            {"step": 6, "label": "Placement/Startup", "detail": "Campus placement or startup journey"},
        ],
        "salary_range": {"min": 600000, "max": 4000000, "currency": "INR", "label": "₹6L – ₹40L+/year"},
        "demand_level": "very_high",
        "top_colleges": ["IIT Bombay", "IIT Delhi", "BITS Pilani", "NIT Trichy", "IIIT Hyderabad"],
        "entrance_exams": ["JEE Main", "JEE Advanced", "BITSAT", "VITEEE"],
        "future_demand": "Extremely high — AI, cloud computing, and digital transformation are driving 30%+ annual growth in software jobs.",
        "icon": "laptop-code",
        "color": "#4F46E5",
    },
    {
        "title": "AI / ML Engineer",
        "category": "Engineering",
        "slug": "ai-ml-engineer",
        "overview": "Build intelligent systems using machine learning and artificial intelligence. The hottest field of the decade with massive salary potential.",
        "required_subjects": ["Mathematics", "Statistics", "Computer Science", "Physics"],
        "skills_required": ["Python", "Machine Learning", "Deep Learning", "Mathematics", "Data Analysis", "Neural Networks"],
        "roadmap_steps": [
            {"step": 1, "label": "Class 10", "detail": "Excel in Mathematics and Science"},
            {"step": 2, "label": "Class 11-12", "detail": "PCM + Computer Science"},
            {"step": 3, "label": "B.Tech/B.Sc", "detail": "CS/AI/Data Science degree"},
            {"step": 4, "label": "Python & ML", "detail": "Learn Python, NumPy, Pandas, scikit-learn"},
            {"step": 5, "label": "Deep Learning", "detail": "TensorFlow/PyTorch, neural networks"},
            {"step": 6, "label": "Projects & Kaggle", "detail": "Build portfolio, compete on Kaggle"},
        ],
        "salary_range": {"min": 800000, "max": 6000000, "currency": "INR", "label": "₹8L – ₹60L+/year"},
        "demand_level": "very_high",
        "top_colleges": ["IIT Bombay", "IISc Bangalore", "IIT Madras", "IIIT Hyderabad", "CMI Chennai"],
        "entrance_exams": ["JEE Main", "JEE Advanced", "GATE (for M.Tech)"],
        "future_demand": "AI engineers are among the most sought-after professionals globally. 100M+ AI jobs projected by 2030.",
        "icon": "robot",
        "color": "#7C3AED",
    },
    {
        "title": "Mechanical Engineer",
        "category": "Engineering",
        "slug": "mechanical-engineer",
        "overview": "Design and manufacture machines, vehicles, and industrial equipment. Core to manufacturing, automotive, and aerospace industries.",
        "required_subjects": ["Mathematics", "Physics", "Chemistry"],
        "skills_required": ["CAD/CAM", "Thermodynamics", "Material Science", "Manufacturing Processes", "AutoCAD"],
        "roadmap_steps": [
            {"step": 1, "label": "Class 10", "detail": "Focus on Physics and Mathematics"},
            {"step": 2, "label": "PCM Stream", "detail": "Physics, Chemistry, Mathematics in 11-12"},
            {"step": 3, "label": "JEE / State CET", "detail": "Engineering entrance exams"},
            {"step": 4, "label": "B.Tech Mechanical", "detail": "4-year mechanical engineering degree"},
            {"step": 5, "label": "CAD Tools", "detail": "Learn SolidWorks, AutoCAD, CATIA"},
            {"step": 6, "label": "Core Industry / GATE", "detail": "Join manufacturing/aerospace or pursue M.Tech"},
        ],
        "salary_range": {"min": 400000, "max": 1800000, "currency": "INR", "label": "₹4L – ₹18L/year"},
        "demand_level": "high",
        "top_colleges": ["IIT Bombay", "IIT Kharagpur", "NIT Surathkal", "VIT Vellore"],
        "entrance_exams": ["JEE Main", "JEE Advanced", "State CETs"],
        "future_demand": "Strong in EV, aerospace, and robotics sectors. EV revolution creating 200,000+ new mechanical jobs in India.",
        "icon": "cog",
        "color": "#0891B2",
    },
    {
        "title": "Civil Engineer",
        "category": "Engineering",
        "slug": "civil-engineer",
        "overview": "Plan, design and oversee construction of infrastructure — roads, bridges, buildings, dams, and cities.",
        "required_subjects": ["Mathematics", "Physics", "Chemistry"],
        "skills_required": ["Structural Analysis", "AutoCAD", "Project Management", "Surveying", "Material Science"],
        "roadmap_steps": [
            {"step": 1, "label": "Class 10", "detail": "Strong in Math and Physics"},
            {"step": 2, "label": "PCM Stream", "detail": "Class 11-12 with PCM"},
            {"step": 3, "label": "JEE / State CET", "detail": "Engineering entrance exams"},
            {"step": 4, "label": "B.Tech Civil", "detail": "4-year civil engineering degree"},
            {"step": 5, "label": "Specialization", "detail": "Structural, Environmental, Transportation"},
            {"step": 6, "label": "Govt / Private", "detail": "PSU jobs, private firms, or UPSC for IES"},
        ],
        "salary_range": {"min": 350000, "max": 1500000, "currency": "INR", "label": "₹3.5L – ₹15L/year"},
        "demand_level": "high",
        "top_colleges": ["IIT Roorkee", "IIT Bombay", "NIT Calicut", "Delhi Tech University"],
        "entrance_exams": ["JEE Main", "JEE Advanced", "State CETs", "GATE"],
        "future_demand": "Smart cities and infrastructure push under PM Gati Shakti creating 3M+ civil engineering jobs through 2030.",
        "icon": "building",
        "color": "#F59E0B",
    },
    # ── Medical ───────────────────────────────────────────────────────────────
    {
        "title": "Doctor (MBBS / MD)",
        "category": "Medical",
        "slug": "doctor-mbbs",
        "overview": "Diagnose and treat illnesses, injuries, and conditions. One of the most respected and impactful professions with strong societal contribution.",
        "required_subjects": ["Biology", "Chemistry", "Physics"],
        "skills_required": ["Biology", "Human Anatomy", "Clinical Skills", "Pharmacology", "Patient Communication"],
        "roadmap_steps": [
            {"step": 1, "label": "Class 10", "detail": "Strong foundation in Science"},
            {"step": 2, "label": "PCB Stream", "detail": "Physics, Chemistry, Biology in 11-12"},
            {"step": 3, "label": "NEET Prep", "detail": "Rigorous NEET UG preparation — 2+ years"},
            {"step": 4, "label": "MBBS", "detail": "5.5 years including 1-year internship"},
            {"step": 5, "label": "NEET-PG", "detail": "Crack NEET-PG for MD/MS specialisation"},
            {"step": 6, "label": "Practice", "detail": "Hospital, clinic, or research career"},
        ],
        "salary_range": {"min": 600000, "max": 5000000, "currency": "INR", "label": "₹6L – ₹50L+/year"},
        "demand_level": "very_high",
        "top_colleges": ["AIIMS Delhi", "JIPMER Puducherry", "CMC Vellore", "MAMC Delhi", "KMC Manipal"],
        "entrance_exams": ["NEET UG", "AIIMS (merged with NEET)", "NEET PG"],
        "future_demand": "India needs 600,000+ more doctors. Healthcare sector growing at 22% annually.",
        "icon": "stethoscope",
        "color": "#10B981",
    },
    {
        "title": "Pharmacist",
        "category": "Medical",
        "slug": "pharmacist",
        "overview": "Prepare and dispense medicines, counsel patients on medications, and work in drug research and development.",
        "required_subjects": ["Chemistry", "Biology", "Mathematics"],
        "skills_required": ["Pharmaceutical Chemistry", "Pharmacology", "Drug Formulation", "Clinical Research"],
        "roadmap_steps": [
            {"step": 1, "label": "Class 10", "detail": "Good in Chemistry and Biology"},
            {"step": 2, "label": "PCB/PCM Stream", "detail": "Class 11-12"},
            {"step": 3, "label": "D.Pharm/B.Pharm", "detail": "2-year diploma or 4-year degree"},
            {"step": 4, "label": "M.Pharm", "detail": "Specialisation in pharmaceutics, clinical pharmacy"},
            {"step": 5, "label": "Career Paths", "detail": "Hospital pharmacy, retail, R&D, regulatory"},
        ],
        "salary_range": {"min": 250000, "max": 1200000, "currency": "INR", "label": "₹2.5L – ₹12L/year"},
        "demand_level": "high",
        "top_colleges": ["BITS Pilani", "JSS Mysuru", "ICT Mumbai", "Jamia Hamdard"],
        "entrance_exams": ["GPAT", "State Pharmacy CETs"],
        "future_demand": "Pharma sector growing at 12%+ driven by generic drugs and biotech — strong employment prospects.",
        "icon": "pills",
        "color": "#059669",
    },
    # ── Government / Civil Services ───────────────────────────────────────────
    {
        "title": "IAS Officer",
        "category": "Government",
        "slug": "ias-officer",
        "overview": "Administer districts and states, implement government policies, and serve as the backbone of Indian administration. One of the most prestigious careers.",
        "required_subjects": ["Social Studies", "History", "Geography", "Economics", "Mathematics"],
        "skills_required": ["General Knowledge", "Current Affairs", "Essay Writing", "Analytical Thinking", "Leadership"],
        "roadmap_steps": [
            {"step": 1, "label": "Class 10-12", "detail": "Any stream — focus on reading, GK, current affairs"},
            {"step": 2, "label": "Graduation", "detail": "Any bachelor's degree (any subject/university)"},
            {"step": 3, "label": "UPSC Prep", "detail": "1-3 years intensive UPSC CSE preparation"},
            {"step": 4, "label": "Prelims", "detail": "2-paper objective exam (GS + CSAT)"},
            {"step": 5, "label": "Mains", "detail": "9-paper written examination"},
            {"step": 6, "label": "Interview + Training", "detail": "Personality test → LBSNAA training"},
        ],
        "salary_range": {"min": 600000, "max": 2500000, "currency": "INR", "label": "₹6L – ₹25L+/year (+ perks)"},
        "demand_level": "high",
        "top_colleges": ["Any university — IITs, DU, JNU preferred by toppers"],
        "entrance_exams": ["UPSC Civil Services Examination"],
        "future_demand": "Permanent government position with lifelong security, power, and social impact.",
        "icon": "badge-check",
        "color": "#DC2626",
    },
    {
        "title": "IPS Officer",
        "category": "Government",
        "slug": "ips-officer",
        "overview": "Lead police forces, maintain law and order, investigate crimes, and protect citizens. Command and intelligence career with national service.",
        "required_subjects": ["Social Studies", "History", "Geography", "Current Affairs"],
        "skills_required": ["Leadership", "Decision Making", "Physical Fitness", "Law Knowledge", "Crisis Management"],
        "roadmap_steps": [
            {"step": 1, "label": "Class 10-12", "detail": "Any stream — develop leadership and discipline"},
            {"step": 2, "label": "Graduation", "detail": "Any bachelor's degree"},
            {"step": 3, "label": "UPSC CSE", "detail": "Clear UPSC + choose IPS in preference list"},
            {"step": 4, "label": "SVPNPA Training", "detail": "Sardar Vallabhbhai Patel National Police Academy"},
            {"step": 5, "label": "SP Level", "detail": "Start as Assistant SP, rise to SP and beyond"},
        ],
        "salary_range": {"min": 560000, "max": 2200000, "currency": "INR", "label": "₹5.6L – ₹22L+/year (+ perks)"},
        "demand_level": "high",
        "top_colleges": ["Any university"],
        "entrance_exams": ["UPSC Civil Services Examination"],
        "future_demand": "Essential government role — will always have demand. Cybercrime and national security divisions growing rapidly.",
        "icon": "shield-check",
        "color": "#1D4ED8",
    },
    # ── Commerce / Finance ────────────────────────────────────────────────────
    {
        "title": "Chartered Accountant (CA)",
        "category": "Commerce",
        "slug": "chartered-accountant",
        "overview": "Manage financial accounts, auditing, taxation, and business consulting. One of India's most respected professional qualifications.",
        "required_subjects": ["Mathematics", "Accountancy", "Economics", "Business Studies"],
        "skills_required": ["Accounting", "Taxation", "Auditing", "Financial Reporting", "Business Law", "GST"],
        "roadmap_steps": [
            {"step": 1, "label": "Class 10", "detail": "Strong in Mathematics and Accountancy"},
            {"step": 2, "label": "Commerce Stream", "detail": "Class 11-12 with Accounts, Business, Economics"},
            {"step": 3, "label": "CA Foundation", "detail": "After Class 12 — 4 subjects exam"},
            {"step": 4, "label": "CA Intermediate", "detail": "8 subjects + 3 years articleship"},
            {"step": 5, "label": "CA Final", "detail": "Advanced exam — highest qualification"},
            {"step": 6, "label": "Practice / Big4", "detail": "Start own firm or join Deloitte/PwC/EY/KPMG"},
        ],
        "salary_range": {"min": 700000, "max": 4000000, "currency": "INR", "label": "₹7L – ₹40L+/year"},
        "demand_level": "very_high",
        "top_colleges": ["ICAI (direct — no college needed)", "DU, Mumbai for B.Com alongside"],
        "entrance_exams": ["CA Foundation", "CA Intermediate", "CA Final (ICAI)"],
        "future_demand": "Every company needs CAs for compliance, GST, and financial reporting. Extremely stable profession.",
        "icon": "calculator",
        "color": "#0891B2",
    },
    {
        "title": "Investment Banker",
        "category": "Commerce",
        "slug": "investment-banker",
        "overview": "Facilitate mergers, acquisitions, and capital raising for corporations and governments. One of the highest-paying finance careers.",
        "required_subjects": ["Mathematics", "Economics", "Business Studies", "Accountancy"],
        "skills_required": ["Financial Modeling", "Valuation", "Excel", "Capital Markets", "Mergers & Acquisitions"],
        "roadmap_steps": [
            {"step": 1, "label": "Class 10-12", "detail": "Commerce or Science stream with strong Math"},
            {"step": 2, "label": "B.Com/BBA/B.Tech", "detail": "From top college"},
            {"step": 3, "label": "CA/CFA/MBA", "detail": "Pursue professional qualifications"},
            {"step": 4, "label": "IIM/IIT MBA", "detail": "CAT exam → prestigious MBA program"},
            {"step": 5, "label": "Internship", "detail": "Investment banking summer internship"},
            {"step": 6, "label": "Analyst Role", "detail": "Join Goldman Sachs, JP Morgan, Kotak, HDFC"},
        ],
        "salary_range": {"min": 1200000, "max": 10000000, "currency": "INR", "label": "₹12L – ₹1Cr+/year"},
        "demand_level": "high",
        "top_colleges": ["IIM Ahmedabad", "IIM Bangalore", "IIT (MBA)", "FMS Delhi", "XLRI"],
        "entrance_exams": ["CAT", "GMAT", "CFA Level 1-3"],
        "future_demand": "India's capital markets growing rapidly — IPO boom and startup ecosystem driving IB demand.",
        "icon": "trending-up",
        "color": "#D97706",
    },
    # ── Law ───────────────────────────────────────────────────────────────────
    {
        "title": "Lawyer / Advocate",
        "category": "Law",
        "slug": "lawyer",
        "overview": "Represent clients in courts, draft legal documents, and provide legal advice. Diverse specialisations from corporate law to criminal law.",
        "required_subjects": ["Social Studies", "History", "English", "Political Science"],
        "skills_required": ["Legal Research", "Argumentation", "Writing", "Critical Thinking", "Constitutional Law"],
        "roadmap_steps": [
            {"step": 1, "label": "Class 10-12", "detail": "Any stream — focus on English and Social Sciences"},
            {"step": 2, "label": "CLAT Prep", "detail": "Prepare for Common Law Admission Test"},
            {"step": 3, "label": "5-Year LLB", "detail": "Integrated BA LLB from NLU or top law school"},
            {"step": 4, "label": "Specialisation", "detail": "Corporate, Criminal, IP, Constitutional, Family law"},
            {"step": 5, "label": "Bar Council", "detail": "Register as advocate with State Bar Council"},
            {"step": 6, "label": "Practice", "detail": "Join law firm, in-house counsel, or independent practice"},
        ],
        "salary_range": {"min": 300000, "max": 5000000, "currency": "INR", "label": "₹3L – ₹50L+/year"},
        "demand_level": "high",
        "top_colleges": ["NLSIU Bangalore", "NALSAR Hyderabad", "NLU Delhi", "ILS Pune", "Symbiosis Law"],
        "entrance_exams": ["CLAT", "AILET", "LSAT India"],
        "future_demand": "Data privacy, cybercrime, and startup ecosystem creating massive demand for tech-savvy lawyers.",
        "icon": "scale",
        "color": "#7C3AED",
    },
    # ── Emerging / Tech ───────────────────────────────────────────────────────
    {
        "title": "Data Scientist",
        "category": "Emerging",
        "slug": "data-scientist",
        "overview": "Extract insights from large datasets using statistics, ML, and visualization. Core to every data-driven business decision.",
        "required_subjects": ["Mathematics", "Statistics", "Computer Science"],
        "skills_required": ["Python/R", "Statistics", "Machine Learning", "SQL", "Data Visualization", "Big Data"],
        "roadmap_steps": [
            {"step": 1, "label": "Class 10-12", "detail": "PCM stream with strong Math & Stats"},
            {"step": 2, "label": "B.Tech/B.Sc", "detail": "CS, Statistics, or Data Science degree"},
            {"step": 3, "label": "Python & SQL", "detail": "Core data manipulation tools"},
            {"step": 4, "label": "ML & Statistics", "detail": "Probability, regression, classification"},
            {"step": 5, "label": "Projects", "detail": "Kaggle competitions, Tableau dashboards"},
            {"step": 6, "label": "Industry Role", "detail": "Analytics at tech/startup/finance companies"},
        ],
        "salary_range": {"min": 700000, "max": 3500000, "currency": "INR", "label": "₹7L – ₹35L+/year"},
        "demand_level": "very_high",
        "top_colleges": ["IISc", "IITs", "ISI Kolkata", "CMI", "IIT Bombay (M.Tech DS)"],
        "entrance_exams": ["JEE Main/Advanced", "JAM (for M.Sc)"],
        "future_demand": "Every industry is becoming data-driven. 11M data science jobs projected in India by 2026.",
        "icon": "chart-bar",
        "color": "#EC4899",
    },
    {
        "title": "Cybersecurity Expert",
        "category": "Emerging",
        "slug": "cybersecurity-expert",
        "overview": "Protect computer systems, networks, and data from cyber attacks. Critical infrastructure security role in a world of rising digital threats.",
        "required_subjects": ["Computer Science", "Mathematics", "Physics"],
        "skills_required": ["Network Security", "Ethical Hacking", "Cryptography", "Python", "Linux", "Penetration Testing"],
        "roadmap_steps": [
            {"step": 1, "label": "Class 10-12", "detail": "PCM + Computer Science"},
            {"step": 2, "label": "B.Tech CS/IT", "detail": "Computer Science engineering"},
            {"step": 3, "label": "Certifications", "detail": "CEH, OSCP, CompTIA Security+"},
            {"step": 4, "label": "CTF Competitions", "detail": "Capture The Flag security competitions"},
            {"step": 5, "label": "Bug Bounty", "detail": "Find vulnerabilities on HackerOne/Bugcrowd"},
            {"step": 6, "label": "SOC/Red Team", "detail": "Security analyst or offensive security role"},
        ],
        "salary_range": {"min": 600000, "max": 4000000, "currency": "INR", "label": "₹6L – ₹40L+/year"},
        "demand_level": "very_high",
        "top_colleges": ["IIT Kanpur", "IIIT Hyderabad", "NIT Trichy", "DTU Delhi"],
        "entrance_exams": ["JEE Main", "BITSAT", "CEH (professional cert)"],
        "future_demand": "Cyberattacks increased 300% post-pandemic. India's cybersecurity market reaching $13.6B by 2025.",
        "icon": "shield",
        "color": "#EF4444",
    },
    {
        "title": "Product Manager",
        "category": "Emerging",
        "slug": "product-manager",
        "overview": "Define product vision, collaborate with engineering and design, and drive product strategy. Considered the CEO of a product.",
        "required_subjects": ["Mathematics", "Computer Science", "Economics", "English"],
        "skills_required": ["Strategic Thinking", "User Research", "Data Analysis", "Communication", "Agile", "A/B Testing"],
        "roadmap_steps": [
            {"step": 1, "label": "Class 10-12", "detail": "Any stream — develop communication and analytical skills"},
            {"step": 2, "label": "Engineering/BBA", "detail": "CS background preferred but not mandatory"},
            {"step": 3, "label": "Build Products", "detail": "Start side projects, apps, student ventures"},
            {"step": 4, "label": "MBA (optional)", "detail": "IIM MBA helps accelerate to senior PM roles"},
            {"step": 5, "label": "APM Program", "detail": "Associate PM programs at Google, Amazon, Flipkart"},
            {"step": 6, "label": "Senior PM", "detail": "Lead products with millions of users"},
        ],
        "salary_range": {"min": 1500000, "max": 8000000, "currency": "INR", "label": "₹15L – ₹80L+/year"},
        "demand_level": "very_high",
        "top_colleges": ["IIT Bombay", "IIM Ahmedabad", "IIT Delhi (MBA)", "ISB Hyderabad"],
        "entrance_exams": ["CAT", "GMAT", "JEE (for CS background)"],
        "future_demand": "Every tech company needs PMs. Remote/global PMs from India working for US companies increasingly common.",
        "icon": "briefcase",
        "color": "#0891B2",
    },
    {
        "title": "UI/UX Designer",
        "category": "Emerging",
        "slug": "ui-ux-designer",
        "overview": "Design intuitive and beautiful digital interfaces that users love. Bridge between technology and human experience.",
        "required_subjects": ["Computer Science", "Art/Design", "English"],
        "skills_required": ["Figma", "User Research", "Prototyping", "Visual Design", "Design Thinking", "HTML/CSS"],
        "roadmap_steps": [
            {"step": 1, "label": "Class 10-12", "detail": "Any stream — develop aesthetic sense and curiosity"},
            {"step": 2, "label": "Design/CS Degree", "detail": "B.Des, B.Tech CS, or Fine Arts"},
            {"step": 3, "label": "Learn Figma", "detail": "Industry-standard design tool — free to learn"},
            {"step": 4, "label": "Build Portfolio", "detail": "Redesign popular apps, create case studies"},
            {"step": 5, "label": "Internship", "detail": "Work on real product design challenges"},
            {"step": 6, "label": "Senior Designer", "detail": "Product Designer → Senior → Design Lead"},
        ],
        "salary_range": {"min": 400000, "max": 2500000, "currency": "INR", "label": "₹4L – ₹25L+/year"},
        "demand_level": "high",
        "top_colleges": ["NID Ahmedabad", "IDC IIT Bombay", "Srishti Bangalore", "MIT Institute of Design"],
        "entrance_exams": ["NID DAT", "NIFT", "UCEED (IIT Design)"],
        "future_demand": "Every app and website needs UX. Design-led companies outperform by 211% — PM for design roles is booming.",
        "icon": "paint-brush",
        "color": "#F97316",
    },
    # ── Defense ───────────────────────────────────────────────────────────────
    {
        "title": "Indian Army Officer",
        "category": "Defense",
        "slug": "army-officer",
        "overview": "Lead and serve in India's army, protecting national borders and maintaining security. One of the most disciplined and respected careers.",
        "required_subjects": ["Mathematics", "Physics", "English"],
        "skills_required": ["Physical Fitness", "Leadership", "Decision Making", "Tactical Planning", "Teamwork"],
        "roadmap_steps": [
            {"step": 1, "label": "Class 10-12", "detail": "PCM recommended, focus on fitness"},
            {"step": 2, "label": "NDA Exam", "detail": "After Class 12 — UPSC NDA/NA exam"},
            {"step": 3, "label": "SSB Interview", "detail": "Services Selection Board — 5-day assessment"},
            {"step": 4, "label": "NDA Training", "detail": "3-year training at National Defence Academy, Pune"},
            {"step": 5, "label": "IMA Training", "detail": "Indian Military Academy — 1 year"},
            {"step": 6, "label": "Commissioned Officer", "detail": "Lieutenant → Captain → Major → Colonel+"},
        ],
        "salary_range": {"min": 560000, "max": 2000000, "currency": "INR", "label": "₹5.6L – ₹20L+/year (+ allowances)"},
        "demand_level": "high",
        "top_colleges": ["NDA Pune", "IMA Dehradun", "OTA Chennai"],
        "entrance_exams": ["UPSC NDA/NA", "UPSC CDS", "TES (Technical Entry)"],
        "future_demand": "Permanent career with strong pension, housing, and perks. Defence modernisation creating tech-focused officer roles.",
        "icon": "military",
        "color": "#065F46",
    },
    # ── Creative ──────────────────────────────────────────────────────────────
    {
        "title": "Journalist / Media Professional",
        "category": "Creative",
        "slug": "journalist",
        "overview": "Research, write, and report on news and events. Shape public opinion and bring important stories to light across print, TV, and digital media.",
        "required_subjects": ["English", "Social Studies", "History", "Political Science"],
        "skills_required": ["Writing", "Research", "Interviewing", "Video Production", "Social Media", "Critical Thinking"],
        "roadmap_steps": [
            {"step": 1, "label": "Class 10-12", "detail": "Arts/Humanities stream — strong in English"},
            {"step": 2, "label": "BA Journalism", "detail": "3-year journalism and mass communication degree"},
            {"step": 3, "label": "College Media", "detail": "College newspaper, radio, YouTube channel"},
            {"step": 4, "label": "Internship", "detail": "Regional newspaper or TV channel internship"},
            {"step": 5, "label": "Beat Reporting", "detail": "Choose specialisation: politics, sports, tech, business"},
            {"step": 6, "label": "Senior Role", "detail": "Senior Correspondent → Editor → Bureau Chief"},
        ],
        "salary_range": {"min": 250000, "max": 2000000, "currency": "INR", "label": "₹2.5L – ₹20L+/year"},
        "demand_level": "medium",
        "top_colleges": ["IIMC Delhi", "ACJ Chennai", "Symbiosis Pune", "JMI Delhi", "XIC Mumbai"],
        "entrance_exams": ["IIMC Entrance", "ACJ Entrance", "University-specific tests"],
        "future_demand": "Digital journalism, podcasting, and YouTube journalism creating new-age media careers with massive reach.",
        "icon": "newspaper",
        "color": "#6B7280",
    },
    # ── Science / Research ────────────────────────────────────────────────────
    {
        "title": "Research Scientist",
        "category": "Science",
        "slug": "research-scientist",
        "overview": "Conduct experiments and studies to advance human knowledge. Push the boundaries of what we know in physics, chemistry, biology, and beyond.",
        "required_subjects": ["Physics", "Chemistry", "Biology", "Mathematics"],
        "skills_required": ["Research Methodology", "Lab Skills", "Data Analysis", "Scientific Writing", "Critical Thinking"],
        "roadmap_steps": [
            {"step": 1, "label": "Class 10-12", "detail": "PCM or PCB with distinction"},
            {"step": 2, "label": "B.Sc/B.Tech", "detail": "From IISc, IIT, or top university"},
            {"step": 3, "label": "M.Sc/M.Tech", "detail": "Specialise in chosen research area"},
            {"step": 4, "label": "PhD", "detail": "Original research contribution — 4-6 years"},
            {"step": 5, "label": "Postdoc", "detail": "Post-doctoral research at IIT/IISc/abroad"},
            {"step": 6, "label": "Faculty/Industry R&D", "detail": "Professor or corporate research lab"},
        ],
        "salary_range": {"min": 500000, "max": 2500000, "currency": "INR", "label": "₹5L – ₹25L/year"},
        "demand_level": "high",
        "top_colleges": ["IISc Bangalore", "TIFR Mumbai", "IIT Bombay", "IISER Pune", "JNCASR"],
        "entrance_exams": ["JEE Advanced", "KVPY", "IISER Aptitude", "JAM", "GATE"],
        "future_demand": "India aiming to be global R&D hub. PM NRF fund allocating ₹50,000 Cr for research through 2028.",
        "icon": "flask",
        "color": "#8B5CF6",
    },
]


def get_categories() -> list[str]:
    return sorted(set(c["category"] for c in CAREER_SEED_DATA))
