services:
  admin:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    ports:
      - "3001:80"
    networks:
      - edtech

networks:
  edtech:
    external: true
    name: edtech_net
